site_name: Creative Coding
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown.extensions:
  - pymdownx.hightlight:
    anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/pixelkind
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pixelkind
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pixelkind

copyright: '&copy; 2023 <a href="https://github.com/pixelkind" target="_blank" rel="noopener">Garrit Schaap</a>'
